sudo: false
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - sourceline: 'ppa:cs50/ppa'
          packages:
            - astyle
      env:
        - DESC="Check code style"
        - TEST="true"

    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - DESC="AppImage deploy"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - DESC="dmg deploy"
        - MATRIX_EVAL="COMPILER=clang++"

install:
- if [[ "${TRAVIS_OS_NAME}" = "linux" && -z $TEST ]]; then
    sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty;
    sudo apt update -qq;
    sudo apt search qt510;
    sudo apt install build-essential qt510-meta-minimal/trusty qt510charts-no-lgpl/trusty
    qt510quickcontrols/trusty qt510quickcontrols2/trusty qt510serialport/trusty
    qt510graphicaleffects/trusty qt510svg/trusty qt510scxml/trusty git;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
    brew install qt5;
    chmod -R 755 /usr/local/opt/qt5/*;
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
  fi

script:
- if [ ! -z $TEST ]; then
    ./tools/astyle.sh;
    git diff;
    if ! git diff --quiet --ignore-submodules HEAD 2>/dev/null; then
      echo "Style error ! Run astyle in tools. (./tools/astyle.sh)";
      exit 1;
    fi;
  fi
- if [[ "${TRAVIS_OS_NAME}" = "linux" && -z $TEST ]]; then
    source /opt/qt*/bin/qt*-env.sh;
    git submodule init;
    git submodule update;
    mkdir build;
    cd build;
    qmake ..;
    make;
    mkdir deploy;
    ls ../qml/;
    ls ../qml/imgs;
    cp ../qml/imgs/pingviewer.png deploy/;
    cp ../deploy/pingviewer.desktop deploy/;
    mv pingviewer deploy/;
    wget https://github.com/patrickelectric/stm32flash-code/releases/download/continuous/stm32flash_linux.zip;
    unzip stm32flash_linux.zip;
    chmod +x stm32flash;
    mv stm32flash deploy/;
    ls deploy;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
    mkdir -p deploy/usr/plugins/imageformats/;
    cp /opt/qt510/plugins/imageformats/libqsvg.so deploy/usr/plugins/imageformats/;
    ./linuxdeployqt*.AppImage deploy/pingviewer -verbose=2 -qmldir=../qml -bundle-non-qt-libs;
    ./linuxdeployqt*.AppImage deploy/pingviewer.desktop -verbose=2 -qmldir=../qml -appimage;
    find . | grep AppImage;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    git submodule init;
    git submodule update;
    mkdir build;
    cd build;
    qmake ..;
    make;
    find .;
    wget https://github.com/patrickelectric/stm32flash-code/releases/download/continuous/stm32flash_osx.zip;
    unzip stm32flash_osx.zip;
    chmod +x stm32flash;
    mv stm32flash pingviewer.app/;
    macdeployqt pingviewer.app/ -qmldir=../qml -dmg;
  fi

after_success:
- if [ -z $TEST ]; then
    wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh;
  fi
- if [[ "${TRAVIS_OS_NAME}" = "linux" && -z $TEST ]]; then
    bash ./upload.sh ./pingviewer*.AppImage*;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash ./upload.sh pingviewer*.dmg*; fi