dist: xenial

language: minimal

install:
  - sudo pip install mkdocs-material

script:
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/bluerobotics/ping-viewer
  - if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then travis_terminate 0; fi
  - mkdocs gh-deploy --force
